# Project information
site_name: Walkalongs
site_url: https://julkaar9.github.io/
site_author: julkar9
site_description: >-
  Solutions and resources of various technologies that I am currently learning

# Repository
repo_name: julkaar9/walkalongs
repo_url: https://github.com/julkaar9/walkalongs

# Copyright
copyright: Copyright &copy; 2022 Md Julkarnaeen

theme:
  name: material
  # logo: assets/pynimate_logo.png
  # favicon: assets/favicon.png
  features: 
    - content.code.annotate 
    - content.tooltips 
    - navigation.indexes 
    - navigation.sections
    - navigation.tabs 
    - navigation.top
    - navigation.tracking 
    - toc.follow
  palette:
    - scheme: default
      primary: green
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - ORMs:
    - Django ORM:
      - w3school: orms/django/w3school.md
# Customization:
extra:
#   analytics:
#     provider: google
#     property:  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/julkaar9/walkalongs 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences