# Generated by Django 4.1 on 2023-03-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_number', models.IntegerField(db_column='customerNumber', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='customerName', max_length=50)),
                ('contact_last_name', models.CharField(db_column='contactLastName', max_length=50)),
                ('contact_first_name', models.CharField(db_column='contactFirstName', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address_line1', models.CharField(db_column='addressLine1', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_number', models.IntegerField(db_column='orderNumber', primary_key=True, serialize=False)),
                ('order_date', models.DateField(db_column='orderDate')),
                ('require_ddate', models.DateField(db_column='requiredDate')),
                ('shipped_date', models.DateField(blank=True, db_column='shippedDate', null=True)),
                ('status', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
                ('customer_number', models.ForeignKey(db_column='customerNumber', on_delete=django.db.models.deletion.DO_NOTHING, to='customer_db.customers')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
