# Generated by Django 4.1 on 2023-03-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='postalcode',
            new_name='postal_code',
        ),
    ]
