# Generated by Django 4.1 on 2023-03-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_db', '0005_occupation_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='occupation',
        ),
        migrations.AddField(
            model_name='person',
            name='occupation_title',
            field=models.ForeignKey(blank=True, db_column='occupation_title', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='customer_db.occupation'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='avg_salary',
            field=models.DecimalField(db_column='avg_salary', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='title',
            field=models.CharField(db_column='title', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='name', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.PositiveIntegerField(db_column='person_id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='occupation',
            table='occupation',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
