# Generated by Django 4.1 on 2023-04-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_db', '0006_remove_person_occupation_person_occupation_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.PositiveIntegerField(db_column='doctor_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('speciality', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.CharField(choices=[('AB', 'AB'), ('BC', 'BC'), ('MB', 'MB'), ('NB', 'NB'), ('NT', 'NT'), ('NS', 'NS'), ('NU', 'NU'), ('ON', 'ON'), ('PE', 'PE'), ('QC', 'QC'), ('SK', 'SK'), ('YT', 'YT')], db_column='province_id', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='province_name', max_length=64)),
            ],
            options={
                'db_table': 'province_names',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.PositiveIntegerField(db_column='patient_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=32)),
                ('allergies', models.CharField(blank=True, max_length=64, null=True)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('province', models.ForeignKey(blank=True, db_column='province_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='customer_db.provinces')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('diagnosis', models.CharField(max_length=128)),
                ('attending_doctor', models.ForeignKey(db_column='attending_doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_admissions', to='customer_db.doctors')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='customer_db.patients')),
            ],
            options={
                'db_table': 'admissions',
            },
        ),
        migrations.AddConstraint(
            model_name='admissions',
            constraint=models.CheckConstraint(check=models.Q(('admission_date__lte', models.F('discharge_date'))), name='admission_before_discharge'),
        ),
    ]
